### ISSUE TITLE
Duplicate packages (reliable)

### ISSUE THREAD

**Issue by Ploppz** [Ploppz/universe#17]
Using `reliable_unordered` to send `Join`, it still is received twice, contrary to the laminar docs saying that there should be no duplication. (as of 66c1c66)
```
Jul 22 2019 11:17:25.649893910+0200: 128 client: Sent Join
Jul 22 2019 11:17:25.664450790+0200: 128 vxdraw-client: Window resized event, dimensions=LogicalSize { width: 541.1428571428571, height: 600.0 }
Jul 22 2019 11:17:25.698621083+0200: 128 server: Received Join message
Jul 22 2019 11:17:25.717508553+0200: 128 client: Received Welcome message!
Jul 22 2019 11:17:26.491322176+0200: 128 server: Received Join message
Jul 22 2019 11:17:26.502626599+0200: 128 client: Received Welcome message!

```

**Comment by kstrafe** [comment]
Tried heartbeating but still getting 2 messages. Might be a bug in laminar.

**Comment by Ploppz** [comment]
https://github.com/amethyst/laminar/issues/222

Also, I noticed that the game often starts spamming "Remove nonexistent bullet". This could be due to the same bug in laminar (I hope so).

**Comment by kstrafe** [comment]
This was due to DoS protection, the packet would register but the connection would not. It is only after having sent a message that a connection is created, and because these packets were reliable, the client sent the reliable message twice because it never received an ack for the first packet.

We can use unreliable packets for initiating a conversation, which pushes the job of re-sending to the user (the programmer).
